[2024-12-31T10:45:14.830+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-31T10:45:14.854+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_backup1.branch_task manual__2024-12-31T10:32:00.554374+00:00 [queued]>
[2024-12-31T10:45:14.865+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_backup1.branch_task manual__2024-12-31T10:32:00.554374+00:00 [queued]>
[2024-12-31T10:45:14.866+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-31T10:45:14.890+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-12-31 10:32:00.554374+00:00
[2024-12-31T10:45:14.900+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=327) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-31T10:45:14.901+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'final_backup1', 'branch_task', 'manual__2024-12-31T10:32:00.554374+00:00', '--job-id', '1075', '--raw', '--subdir', 'DAGS_FOLDER/final_backup1.py', '--cfg-path', '/tmp/tmp39974pq5']
[2024-12-31T10:45:14.902+0000] {standard_task_runner.py:72} INFO - Started process 329 to run task
[2024-12-31T10:45:14.902+0000] {standard_task_runner.py:105} INFO - Job 1075: Subtask branch_task
[2024-12-31T10:45:14.924+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-31T10:45:14.969+0000] {task_command.py:467} INFO - Running <TaskInstance: final_backup1.branch_task manual__2024-12-31T10:32:00.554374+00:00 [running]> on host 05c0118fb254
[2024-12-31T10:45:15.114+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='final_backup1' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-31T10:32:00.554374+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-31T10:32:00.554374+00:00'
[2024-12-31T10:45:15.116+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-31T10:45:15.120+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-12-31T10:45:15.151+0000] {final_backup1.py:22} INFO - DEBUG: files_to_copy_dict: LazySelectSequence([2 items])
[2024-12-31T10:45:15.154+0000] {python.py:240} INFO - Done. Returned value was: skip_copy
[2024-12-31T10:45:15.155+0000] {branch.py:38} INFO - Branch into skip_copy
[2024-12-31T10:45:15.156+0000] {skipmixin.py:230} INFO - Following branch ('skip_copy',)
[2024-12-31T10:45:15.162+0000] {skipmixin.py:278} INFO - Skipping tasks [('copying_task', -1)]
[2024-12-31T10:45:15.209+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-31T10:45:15.211+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=final_backup1, task_id=branch_task, run_id=manual__2024-12-31T10:32:00.554374+00:00, execution_date=20241231T103200, start_date=20241231T104514, end_date=20241231T104515
[2024-12-31T10:45:15.240+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-31T10:45:15.278+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-31T10:45:15.282+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
